/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const FreeCaseReview = IDL.Record({
  'id' : IDL.Text,
  'carModel' : IDL.Text,
  'fullName' : IDL.Text,
  'email' : IDL.Text,
  'insuranceWithStateFarm' : IDL.Bool,
  'eyeInjury' : IDL.Bool,
  'underMedicalCare' : IDL.Bool,
  'address' : IDL.Text,
  'timestamp' : Time,
  'visionImpaired' : IDL.Bool,
  'hasLawsuit' : IDL.Bool,
  'carMake' : IDL.Text,
  'carYear' : IDL.Text,
  'currentEyeglassesPrescription' : IDL.Text,
  'claimState' : IDL.Text,
  'insuranceClaimNumber' : IDL.Text,
  'phoneNumber' : IDL.Text,
  'laserSurgery' : IDL.Bool,
});

export const idlService = IDL.Service({
  'createReview' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Bool,
        IDL.Text,
        IDL.Text,
        IDL.Bool,
        IDL.Bool,
        IDL.Bool,
        IDL.Text,
        IDL.Bool,
        IDL.Bool,
      ],
      [IDL.Text],
      [],
    ),
  'getAllReviews' : IDL.Func([], [IDL.Vec(FreeCaseReview)], ['query']),
  'getReview' : IDL.Func([IDL.Text], [FreeCaseReview], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const FreeCaseReview = IDL.Record({
    'id' : IDL.Text,
    'carModel' : IDL.Text,
    'fullName' : IDL.Text,
    'email' : IDL.Text,
    'insuranceWithStateFarm' : IDL.Bool,
    'eyeInjury' : IDL.Bool,
    'underMedicalCare' : IDL.Bool,
    'address' : IDL.Text,
    'timestamp' : Time,
    'visionImpaired' : IDL.Bool,
    'hasLawsuit' : IDL.Bool,
    'carMake' : IDL.Text,
    'carYear' : IDL.Text,
    'currentEyeglassesPrescription' : IDL.Text,
    'claimState' : IDL.Text,
    'insuranceClaimNumber' : IDL.Text,
    'phoneNumber' : IDL.Text,
    'laserSurgery' : IDL.Bool,
  });
  
  return IDL.Service({
    'createReview' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Bool,
          IDL.Text,
          IDL.Text,
          IDL.Bool,
          IDL.Bool,
          IDL.Bool,
          IDL.Text,
          IDL.Bool,
          IDL.Bool,
        ],
        [IDL.Text],
        [],
      ),
    'getAllReviews' : IDL.Func([], [IDL.Vec(FreeCaseReview)], ['query']),
    'getReview' : IDL.Func([IDL.Text], [FreeCaseReview], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };