/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface FreeCaseReview {
  'id' : string,
  'carModel' : string,
  'fullName' : string,
  'email' : string,
  'insuranceWithStateFarm' : boolean,
  'eyeInjury' : boolean,
  'underMedicalCare' : boolean,
  'address' : string,
  'timestamp' : Time,
  'visionImpaired' : boolean,
  'hasLawsuit' : boolean,
  'carMake' : string,
  'carYear' : string,
  'currentEyeglassesPrescription' : string,
  'claimState' : string,
  'insuranceClaimNumber' : string,
  'phoneNumber' : string,
  'laserSurgery' : boolean,
}
export type Time = bigint;
export interface _SERVICE {
  'createReview' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      boolean,
      string,
      string,
      boolean,
      boolean,
      boolean,
      string,
      boolean,
      boolean,
    ],
    string
  >,
  'getAllReviews' : ActorMethod<[], Array<FreeCaseReview>>,
  'getReview' : ActorMethod<[string], FreeCaseReview>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];